### ISSUE TITLE
sqlalchemy error upon launch

### ISSUE THREAD

**Issue by drchriscole** [SamStudio8/chitin#15]
Getting an error when launching for the first time. Install (as --user) went smoothly.

Traceback (most recent call last):
  File "/homes/ccole/.local/bin/chitin", line 9, in <module>
    load_entry_point('chitin==0.0.1', 'console_scripts', 'chitin')()
  File "/sw/opt/python/2.7.3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/sw/opt/python/2.7.3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/sw/opt/python/2.7.3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/sw/opt/python/2.7.3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/chitin/__init__.py", line 18, in <module>
    'BufrStubImagePlugin',
  File "build/bdist.linux-x86_64/egg/chitin/util.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/chitin/record.py", line 6, in <module>
  File "/cluster/gjb_lab/ccole/.local/lib/python2.7/site-packages/Flask_SQLAlchemy-2.1-py2.7.egg/flask_sqlalchemy/__init__.py", line 25, in <module>
    from sqlalchemy import orm, event, inspect
ImportError: cannot import name inspect

Could be a dependency issue. What version requirements are there?

**Comment by SamStudio8** [comment]
That's unusual, I just tried to install this in a clean `virtualenv` and
can start `chitin` without error.
When I install this in a new `virtualenv`, SQLAlchemy 1.1.4 gets pulled in
as a dependency of Flask_SQLAlchemy. Do you think it's possible you have a
clashing install of `sqlalchemy`?

```
Installed
/home/sam/venv/lab-test/lib/python2.7/site-packages/Flask_SQLAlchemy-2.1-py2.7.egg
Searching for SQLAlchemy
Reading https://pypi.python.org/simple/SQLAlchemy/
Best match: SQLAlchemy 1.1.4
```

**Comment by SamStudio8** [comment]
Could not reproduce, please re-open if this persists!
